config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'  }

  # resources :squads, only: [:index, :show]


  resources :teams, only: [:show]

  namespace :account do
    resource :profile, only: [:show, :edit, :update]
    resource :squad,   only: [:show, :new, :create, :edit, :update] do
      member do
        get :selection
        get :lineup
        get :captain
      end
    end

    resources :leagues, only: [:index, :show]

    resources :league_players, only: [:create]

    resources :squad_players, only: [:create, :destroy]
    resources :gameweeks, only: [:index, :show]
    resources :gameweek_squad_players, only: [:create, :show]
  end
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-md-4 col-lg-4">
        <ul class="list-inline">
          <li>
            <a href="#"><i class="fa fa-youtube"></i></a>
            </li>
          <li>
            <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
          <li>
            <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
          <li>
            <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
        </ul>
      </div>
      <div class="col-xs-6 col-md-8 col-lg-8 text-right">
        <p>Deviens Manager</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <%= link_to root_path, class:"navbar-wagon-brand" do  %>
  <%= image_tag 'field-logo.png' %>
  <% end %>
  <% if signed_in? %>
  <div class="dropdown">
    <ul class="nav-fantasy-center">
      <li>
        <%= link_to "Mon équipe", account_squad_path %>
      </li>
      <li>
        <%= link_to "Transferts", selection_account_squad_path %>
      </li>
      <li>
        <%= link_to "Mes Points", account_gameweek_path(@gameweek_number) %>
      </li>
      <li>
        <%= link_to "Leagues", account_leagues_path %>
      </li>
    </ul>
  </div>

  <div class="navbar-wagon-right hidden-xs">

    <div class="dropdown">

      <ul class="nav-fantasy">
        <li>
          <% if current_user.nickname.nil? %>

          <li><%=link_to account_profile_path do %>
            <div class="nickname_and_squad">
              <div class="nav-squad">
                <% if current_user.squad.nil? %>
                <%= "No squad yet !" %>
                <% else %>
                <%= current_user.squad.name %>
                <% end %>
              </div>
              <div class="nav-nickname">
                <p>C'est quoi ton p'tit nom?</p>
              </div>
            </div>
            <% end %>
          </li>

          <% else %>
          <li><%=link_to account_profile_path do %>
            <div class="nickname_and_squad">
              <div class="nav-squad">
                <% if current_user.squad.nil? %>
                <%= "No squad yet !" %>
                <% else %>
                <%= current_user.squad.name %>
                <% end %>
              </div>
              <div class="nav-nickname">
                <%= current_user.nickname %>
              </div>
            </div>

            <% end %>
          </li>

          <% end %>
        </li>
        <li>
          <% if current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class:"avatar", data: { toggle: 'dropdown'} %>
          <% else %>
          <%= image_tag 'placeholder.png', class: "avatar",  data: { toggle: 'dropdown'}  %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to 'Profile', account_profile_path %></li>
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>

    </div>
    <% end %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Profile', account_profile_path %></li>
        <li>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</div>