config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  ActiveAdmin.routes(self)

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'  }

  # resources :squads, only: [:index, :show]


  resources :teams, only: [:show]

  namespace :account do
    resource :profile, only: [:show, :edit, :update]
    resource :squad,   only: [:show, :new, :create, :edit, :update] do
      member do
        get :selection
        get :lineup
        get :captain
      end
    end

    resources :leagues, only: [:index, :show]

    resources :league_players, only: [:create]

    resources :squad_players, only: [:create, :destroy]
    resources :gameweeks, only: [:index, :show]
    resources :gameweek_squad_players, only: [:create, :show]
  end
end

app/views/pages/home.html.erb
<div class="banner" style="background-image:url('<%= image_path @background %>')">

  <div class="banner-content text-center">
    <div class="home-title-animation">
      <h1>Fantasy ProLeague</h1>
    </div>
    <p>Crée ton équipe et remporte le titre</p>

    <% unless user_signed_in? %>
    <%= link_to "Se connecter", new_user_session_path, class:"btn btn-default btn-lg" %>
    <% end %>
    <%=link_to 'Commencer à jouer', new_account_squad_path, class:"btn btn-success btn-lg" %>

  </div>
</div>

<div class="text-center padded features">
  <div class="container">
    <div class="row">
      <div class="flaticon">
        <div class="col-xs-12 col-sm-6">
          <%= image_tag('football-field.png') %>
          <h2> Manager </h2>
          <p>Compose ta sélection parmi les joueurs de la Proleague</p>
        </div>
        <div class="col-xs-12 col-sm-6">
         <%= image_tag('game.png') %>
         <h2> Ta compo </h2>
         <p> Chaque semaine, aligne tes 11 joueurs</p>
       </div>
     </div>
   </div>
   <div class="row">
    <div class="col-xs-12 col-sm-6">
     <%= image_tag('football-2.png') %>
     <h2> Gagne</h2>
     <p> En fonction des matches du week-end, tes joueurs gagnent des points  </p>
   </div>
   <div class="col-xs-12 col-sm-6">
     <%= image_tag('football.png') %>
     <h2> Transferts</h2>
     <p> Un joueur blessé? Tu as droit à un transfert par semaine </p>
   </div>
 </div>
</div>
</div>